trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  version: 1.0.2-$(Build.BuildId)

stages:
- stage: Build_Stage
  displayName: 
  jobs:
  - job: BuildNuget
    displayName: Build Nuget packages
    variables:
      BuildConfiguration: release
    steps:

    - task: DotNetCoreCLI@2
      displayName: Restore Packages
      inputs:
        azureSubscription: 'azure-cli-2024-10-14-06-24-51'
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        vstsFeed: '2c1c8360-5dc0-4abf-84f5-33b1851b9f69/f0a09130-bab4-409d-bc2d-4b9b536f2459'

    - task: DotNetCoreCLI@2
      displayName: Build Apps
      inputs:
        azureSubscription: 'azure-cli-2024-10-14-06-24-51'
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - script: printenv

    - task: DotNetCoreCLI@2
      displayName: Pack Nuget Package
      inputs:
        azureSubscription: 'azure-cli-2024-10-14-06-24-51'
        command: 'pack'
        packagesToPack: '**/*.csproj'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'version'

    - task: DotNetCoreCLI@2
      displayName: Push Nuget Package
      inputs:
        azureSubscription: 'azure-cli-2024-10-14-06-24-51'
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '2c1c8360-5dc0-4abf-84f5-33b1851b9f69/f0a09130-bab4-409d-bc2d-4b9b536f2459'